import nodemailer from 'nodemailer';

export default async function handler(req, res) {
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  // Handle browser preflight request
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({
      success: false,
      error: 'Method not allowed'
    });
  }

  const {
    email,
    amount,
    recipientUpi,
    riskScore
  } = req.body || {};

  // Validate email
  if (!email || !email.trim()) {
    return res.status(400).json({
      success: false,
      error: 'Trusted nominee email is required'
    });
  }

  // Get SMTP credentials from environment variables
  const smtpHost = process.env.SMTP_HOST || 'smtp.gmail.com';
  const smtpPort = parseInt(process.env.SMTP_PORT || '465', 10);
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;

  // Make sure credentials exist
  if (!smtpUser || !smtpPass) {
    return res.status(500).json({
      success: false,
      error: 'SMTP credentials are not configured'
    });
  }

  try {
    // Create Gmail SMTP transporter
    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: {
        user: smtpUser,
        pass: smtpPass
      }
    });

    // Email
    const mailOptions = {
      from: `"Trust Shield Security" <${smtpUser}>`,
      to: email,
      subject: '🛡️ Trust Shield - Suspicious Payment Alert',

      html: `
        <div style="
          font-family: Arial, sans-serif;
          background:#0c1220;
          color:#ffffff;
          padding:24px;
          border-radius:12px;
          max-width:520px;
          margin:auto;
        ">

          <div style="
            text-align:center;
            margin-bottom:20px;
          ">
            <h2 style="
              color:#6366f1;
              margin:0;
            ">
              🛡️ Trust Shield
            </h2>

            <p style="
              color:#94a3b8;
              font-size:13px;
            ">
              Trusted Nominee Security Alert
            </p>
          </div>

          <div style="
            background:rgba(239,68,68,0.12);
            border:1px solid rgba(239,68,68,0.35);
            padding:18px;
            border-radius:10px;
          ">

            <h3 style="color:#f87171;margin-top:0;">
              ⚠️ Suspicious Payment Detected
            </h3>

            <p style="
              color:#cbd5e1;
              font-size:14px;
              line-height:1.5;
            ">
              Trust Shield detected a potentially fraudulent
              payment attempt.
            </p>

            <p>
              <strong>Amount:</strong>
              ₹${amount || 'Unknown'}
            </p>

            <p>
              <strong>Recipient UPI:</strong>
              ${recipientUpi || 'Unknown'}
            </p>

            <p>
              <strong>Risk Score:</strong>
              ${riskScore ?? 'Unknown'}/100
            </p>

          </div>

          <div style="
            margin-top:16px;
            padding:14px;
            background:rgba(245,158,11,0.12);
            border:1px solid rgba(245,158,11,0.3);
            border-radius:8px;
            color:#fbbf24;
            font-size:13px;
            line-height:1.5;
          ">
            <strong>Security Warning</strong><br/>
            Please contact the account holder and verify this
            transaction before allowing the payment to proceed.
          </div>

          <p style="
            color:#64748b;
            font-size:11px;
            text-align:center;
            margin-top:20px;
          ">
            This alert was automatically generated by Trust Shield.
          </p>

        </div>
      `
    };

    // Actually send the email
    await transporter.sendMail(mailOptions);

    return res.status(200).json({
      success: true,
      message: 'Scam alert sent successfully'
    });

  } catch (err) {
    console.error('Scam alert email error:', err);

    return res.status(500).json({
      success: false,
      error: 'Failed to send scam alert'
    });
  }
}